In [83]:
dataset = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2024)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at anjani.ds@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.ds.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at anjani.ds@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at anjani.ds@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [84]:
import tensorflow
from tensorflow import keras
from keras.preprocessing.text import Tokenizer

In [85]:
token=Tokenizer()

In [86]:
token.fit_on_texts([dataset])

In [87]:
token.word_index

{'the': 1,
 'you': 2,
 'i': 3,
 'to': 4,
 'a': 5,
 'is': 6,
 'have': 7,
 'of': 8,
 'will': 9,
 'what': 10,
 'can': 11,
 'course': 12,
 'program': 13,
 'for': 14,
 'in': 15,
 'all': 16,
 'sessions': 17,
 'on': 18,
 'be': 19,
 'and': 20,
 'if': 21,
 'am': 22,
 'pay': 23,
 'payment': 24,
 'make': 25,
 'we': 26,
 'this': 27,
 'do': 28,
 'subscription': 29,
 'rs': 30,
 'so': 31,
 'session': 32,
 'our': 33,
 'paid': 34,
 'join': 35,
 'able': 36,
 'your': 37,
 'website': 38,
 'placement': 39,
 'fee': 40,
 'monthly': 41,
 'where': 42,
 'not': 43,
 'get': 44,
 'yes': 45,
 'once': 46,
 'past': 47,
 'feb': 48,
 'assistance': 49,
 'data': 50,
 '7': 51,
 '5600': 52,
 'are': 53,
 'watch': 54,
 'mail': 55,
 'from': 56,
 'contact': 57,
 'us': 58,
 'at': 59,
 'ds': 60,
 'or': 61,
 'doubt': 62,
 'science': 63,
 'payments': 64,
 '799': 65,
 'month': 66,
 'total': 67,
 'duration': 68,
 'months': 69,
 'learning': 70,
 'case': 71,
 'here': 72,
 'part': 73,
 'by': 74,
 'late': 75,
 'dashboard': 76,
 'task': 

In [88]:
len(token.word_index)

266

In [89]:
input_sequence=[]
for sentense in dataset.split('\n'):
  tokenized_sentenses=token.texts_to_sequences([sentense])[0]

  for i in range(1,len(tokenized_sentenses)):
    input_sequence.append(tokenized_sentenses[:i+1])

In [90]:
input_sequence

[[89, 1],
 [89, 1, 13],
 [10, 6],
 [10, 6, 1],
 [10, 6, 1, 12],
 [10, 6, 1, 12, 40],
 [10, 6, 1, 12, 40, 14],
 [10, 6, 1, 12, 40, 14, 50],
 [10, 6, 1, 12, 40, 14, 50, 63],
 [10, 6, 1, 12, 40, 14, 50, 63, 90],
 [10, 6, 1, 12, 40, 14, 50, 63, 90, 13],
 [10, 6, 1, 12, 40, 14, 50, 63, 90, 13, 144],
 [10, 6, 1, 12, 40, 14, 50, 63, 90, 13, 144, 91],
 [1, 12],
 [1, 12, 92],
 [1, 12, 92, 5],
 [1, 12, 92, 5, 41],
 [1, 12, 92, 5, 41, 29],
 [1, 12, 92, 5, 41, 29, 93],
 [1, 12, 92, 5, 41, 29, 93, 42],
 [1, 12, 92, 5, 41, 29, 93, 42, 2],
 [1, 12, 92, 5, 41, 29, 93, 42, 2, 7],
 [1, 12, 92, 5, 41, 29, 93, 42, 2, 7, 4],
 [1, 12, 92, 5, 41, 29, 93, 42, 2, 7, 4, 25],
 [1, 12, 92, 5, 41, 29, 93, 42, 2, 7, 4, 25, 41],
 [1, 12, 92, 5, 41, 29, 93, 42, 2, 7, 4, 25, 41, 64],
 [1, 12, 92, 5, 41, 29, 93, 42, 2, 7, 4, 25, 41, 64, 8],
 [1, 12, 92, 5, 41, 29, 93, 42, 2, 7, 4, 25, 41, 64, 8, 30],
 [1, 12, 92, 5, 41, 29, 93, 42, 2, 7, 4, 25, 41, 64, 8, 30, 65],
 [1, 12, 92, 5, 41, 29, 93, 42, 2, 7, 4, 25, 41, 64, 8,

In [91]:
max_len=max([len(x) for x in input_sequence])

In [92]:
from keras.preprocessing.sequence import pad_sequences
padded_input_sequence=pad_sequences(input_sequence,maxlen=max_len,padding='pre')

In [93]:
padded_input_sequence

array([[  0,   0,   0, ...,   0,  89,   1],
       [  0,   0,   0, ...,  89,   1,  13],
       [  0,   0,   0, ...,   0,  10,   6],
       ...,
       [  0,   0,   0, ..., 263,  18, 264],
       [  0,   0,   0, ...,  18, 264, 265],
       [  0,   0,   0, ..., 264, 265, 266]], dtype=int32)

In [94]:
X=padded_input_sequence[:,:-1]

In [95]:
y=padded_input_sequence[:,-1]

In [96]:
X

array([[  0,   0,   0, ...,   0,   0,  89],
       [  0,   0,   0, ...,   0,  89,   1],
       [  0,   0,   0, ...,   0,   0,  10],
       ...,
       [  0,   0,   0, ...,   0, 263,  18],
       [  0,   0,   0, ..., 263,  18, 264],
       [  0,   0,   0, ...,  18, 264, 265]], dtype=int32)

In [97]:
len(y)

822

In [98]:
from keras.utils import to_categorical
y=to_categorical(y,num_classes=283)

In [99]:
y.shape

(822, 283)

In [100]:
y[0]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [101]:
from keras.models import Sequential
from keras.layers import Embedding,LSTM,Dense

In [102]:
model=Sequential()

In [103]:
model.add(Embedding(283,100,input_length=56))
model.add(LSTM(150))
model.add(Dense(283,activation='softmax'))

In [104]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [105]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 56, 100)           28300     
                                                                 
 lstm_4 (LSTM)               (None, 150)               150600    
                                                                 
 dense_2 (Dense)             (None, 283)               42733     
                                                                 
Total params: 221633 (865.75 KB)
Trainable params: 221633 (865.75 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [106]:
model.fit(X,y,epochs=100)

Epoch 1/100
26/26 [==============================] - 3s 57ms/step - loss: 5.4624 - accuracy: 0.0645
Epoch 2/100
26/26 [==============================] - 2s 59ms/step - loss: 5.0581 - accuracy: 0.0791
Epoch 3/100
26/26 [==============================] - 1s 56ms/step - loss: 4.9795 - accuracy: 0.0791
Epoch 4/100
26/26 [==============================] - 1s 57ms/step - loss: 4.9384 - accuracy: 0.0791
Epoch 5/100
26/26 [==============================] - 1s 57ms/step - loss: 4.9078 - accuracy: 0.0791
Epoch 6/100
26/26 [==============================] - 1s 55ms/step - loss: 4.8416 - accuracy: 0.0852
Epoch 7/100
26/26 [==============================] - 2s 76ms/step - loss: 4.7246 - accuracy: 0.0949
Epoch 8/100
26/26 [==============================] - 2s 82ms/step - loss: 4.5227 - accuracy: 0.1229
Epoch 9/100
26/26 [==============================] - 2s 69ms/step - loss: 4.3041 - accuracy: 0.1460
Epoch 10/100
26/26 [==============================] - 2s 60ms/step - loss: 4.0835 - accuracy: 0.1825

In [107]:
import time
import numpy as np
text = "I have read that Placement assistance"

for i in range(5):
  # tokenize
  token_text = token.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=56, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in token.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 [==============================] - 0s 281ms/step
I have read that Placement assistance is
1/1 [==============================] - 0s 18ms/step
I have read that Placement assistance is a
1/1 [==============================] - 0s 18ms/step
I have read that Placement assistance is a part
1/1 [==============================] - 0s 16ms/step
I have read that Placement assistance is a part of
1/1 [==============================] - 0s 17ms/step
I have read that Placement assistance is a part of this
